services:
  tester:
    # image: python:alpine3.20
    container_name: python_pruebas
    build: .
    command: tail -f /dev/null
    # ports:
    #   - 8081:8080
    environment:
      - VARIABLE3=texto3
    env_file:
      - .env
    # volumes:
    #   - .:/app
