services:
  miguel-db:
    container_name: miguel-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - miguel-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  miguel-postgres-data:
